### ISSUE TITLE
Integration in 'performance::check_outliers'

### ISSUE THREAD

**Issue by DominiqueMakowski** [privefl/bigutilsr#1]
Hey @privefl, just came across your nice blogpost, which was totally in line with our recent addition in the ['performance'](https://github.com/easystats/performance), in which we added a composite outlier detection helper that aggregates different methods together.

I also added (currently on the dev branch) support for your package and its reexport of covRob (see [here](https://github.com/easystats/performance/blob/dev/R/check_outliers.R#L374)), as well as support for the [lof method](https://github.com/easystats/performance/blob/dev/R/check_outliers.R#L529).

(unfortunately, I couldn't manage to install your package as I believe the binaries for windows on CRAN were still not built (due to the upload recency). 

Anyway, we'd be glad to have your input on the `check_outliers` function, regarding the parameters or the thresholds used. Do not hesitate to give us some feedback, opinions and thoughts :)

**Comment by privefl** [comment]
Thanks for the feedback.

I see that we may have different use of outlier detection. Yours focuses on models and visual inspection whereas I would like to use it in an automatic procedure that (re-)computes PCA until there is no outlier left. I also need the algorithm to be fast as I will use them on datasets as large as 1M samples.
I'll look into the methods used in `check_outliers()` and give you some feedback.

You can install {bigutilsr} from GitHub. 
CRAN binaries should be available in a few days.

**Comment by privefl** [comment]
I see that you're also using some robust Mahalanobis distance ("MCD").
For my problem, I've tested the ones that you can use in `covRob()` and only the pairwise estimators were giving satisfactory results (for my problem).

E.g. look at
```
X <- readRDS(system.file("testdata", "three-pops.rds", package = "bigutilsr"))
pca <- prcomp(X, scale. = TRUE, rank. = 10)
U <- pca$x

library(bigutilsr)
dist <- sqrt(covRob(U, estim = "MCD")$dist)
# dist <- sqrt(covRob(U, estim = "pairwiseGK")$dist)
library(ggplot2)
theme_set(bigstatsr::theme_bigstatsr(0.8))
qplot(U[, 1], U[, 2], color = dist) + coord_equal() + 
  scale_color_viridis_c()
```

This problems might happen when the data is not really normally distributed.

**Comment by DominiqueMakowski** [comment]
Thanks! And what would be your suggestions for a cut-off value for LOF?

**Comment by privefl** [comment]
For now, I'm using `tukey_mc_up()`.
You might want to transform your statistic before using it (e.g. `log()` or `sqrt()`) to make it "more normal". 
For example, I return the logarithm of LOF by default.

**Comment by privefl** [comment]
I've tested the statistics you provide in {performance}.
It seems that none works better than LOF *for my use case*.

However, I discovered some I didn't know and that could become handy for other problems. 
Thanks

**Comment by DominiqueMakowski** [comment]
> For now, I'm using tukey_mc_up()

You're right, we might use that for LOF, and do you think it's a better thresholding method than the current one that we use for Mahalabonis distance (based on the Chisq distrib)?

> It seems that none works better than LOF for my use case.

That's interesting! I'd like to see a pragmatic comparison of these methods, and which performs the best in which cases, and see if our "composite index" that aggregates multiple methods does better on average than single methods... but that's another topic ☺️ 

I'll close this issue then, thanks and do not hesitate bump in if you have any ideas/thoughts. Cheers!

**Comment by privefl** [comment]
One problem I see with Mahalanobis distance is the number of degrees of freedom.
If all variables are independent, then it might be fine. If not, p-values can be off.
