### ISSUE TITLE
How to convert bed/bim/fam or vcf files to the package input

### ISSUE THREAD

**Issue by aydaraliev** [privefl/bigutilsr#8]
I want to detect outlier samples, but I can't figure out how do I convert my bed/bim/fam or vcf files to input to this package. Do you have any examples of such conversion? readRDS function is confusing, because summary() function outputs just V1 V2 V3 etc. columns.

**Comment by privefl** [comment]
To compute PCA on bed/bim/fam, you can use either R package bigsnpr or pcadapt.

**Comment by aydaraliev** [comment]
> To compute PCA on bed/bim/fam, you can use either R package bigsnpr or pcadapt.

Sorry for the misunderstanding. I wanted to use bigutilsr because you describe how to detect outlying samples in the tutorial. And I can't figure out how to format my initial dataset to an input.

**Comment by privefl** [comment]
The blog post is about detecting outlier samples **in PCA**.
There are way too many variables to apply this to a genotype matrix directly.
So, you first need to apply PCA to your input data, and then you can apply these techniques on the matrix of PC scores.
